# Generated by Django 5.2 on 2025-04-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemongame',
            name='release_date',
            field=models.IntegerField(),
        ),
    ]
