# Generated by Django 5.2 on 2025-04-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_platform_alter_pokemongame_generation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='PokemonGame',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='PokemonGame',
            field=models.ManyToManyField(related_name='pokemons', to='pokemon.pokemongame'),
        ),
    ]
