# Generated by Django 5.2 on 2025-04-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_alter_pokemongame_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
