# Generated by Django 5.2 on 2025-04-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_pokemon_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='caught',
            field=models.BooleanField(default=False),
        ),
    ]
